apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: "seleniumtestautomation"
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: "seleniumtestautomation"
    spec:
      containers:
        - name: "seleniumtestautomation"
          image: "testregistry1233.azurecr.io/seleniumtestautomation"
          ports:
          - containerPort: 8080